version: 2.1
orbs:
  jq: circleci/jq@1.9.0 # needed to install tools from docker orb
  docker: circleci/docker@0.5.0
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.10
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION}}-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
      - run:
          name: "Get deps"
          command: mix deps.get
      - run:
          name: "Compile project"
          command: MIX_ENV=test mix compile --warnings-as-errors
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION}}-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
          paths:
            - deps
            - _build
      - jq/install
      - docker/install-dockerize
      - run:
          name: "Run linter checks"
          command: mix credo
      - run:
          name: "Check code format"
          command: mix format --check-formatted
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
            - '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-{{ .Branch }}-'
            - '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-'
      - run:
          name: "Restore cached dialyzer files"
          command: "mkdir -p plts && ls plts | xargs -I % cp plts/% _build/dev/"
      - run:
          name: "Build dialyzer plt"
          command: mix dialyzer --plt
      - run:
          name: "Prepare dialyzer files to cache"
          command: "mkdir -p plts && ls _build/dev | grep dialyxir | xargs -I % cp _build/dev/% -t plts"
      - save_cache:
          paths:
            - plts
            - ~/.mix
          key: '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
      - run:
          name: "Run Dialyzer checks"
          command: mix dialyzer --halt-exit-status
      - run:
          name: "Run tests"
          command: mix test
